# https://taskfile.dev

version: "3"

tasks:
  check:
    desc: "执行 cargo check 确认编译通过"
    cmds:
      - cargo fmt
      - cargo check

  build:
    desc: "编译项目（release 模式）"
    cmds:
      - cargo build --release
  build:hotpath:
    desc: "编译项目（hotpath 模式）"
    cmds:
      - cargo build --release --features=hotpath

  build:hotpath-alloc-bytes:
    desc: "编译项目（hotpath + 总字节分配统计模式）"
    cmds:
      - cargo build --release --features="hotpath hotpath-alloc-bytes-total"

  galileo:run:
    desc: "运行 galileo CLI，自定义命令通过 CMD 变量传入"
    vars:
      CMD: '{{default "--help" .CMD}}'
    cmds:
      - cargo run -- {{.CMD}}

  galileo:help:
    desc: "查看 galileo CLI 帮助"
    cmds:
      - task: galileo:run
        vars:
          CMD: "--help"

  galileo:init:
    desc: "生成配置模版（支持额外参数传入）"
    cmds:
      - task: galileo:run
        vars:
          CMD: 'init {{.CLI_ARGS | default ""}}'

  galileo:quote:
    desc: "请求报价（需传入必要参数）"
    cmds:
      - task: galileo:run
        vars:
          CMD: 'quote {{.CLI_ARGS | default "--help"}}'

  galileo:strategy:
    desc: "运行套利策略循环"
    cmds:
      - task: galileo:run
        vars:
          CMD: 'strategy {{.CLI_ARGS | default ""}}'

  galileo:hotpath:
    desc: "启用 hotpath 特性运行 galileo（自定义命令通过 CMD 传入）"
    vars:
      CMD: '{{default "strategy" .CMD}}'
    cmds:
      - cargo run --features=hotpath -- {{.CMD}}

  galileo:hotpath:alloc-bytes:
    desc: "启用 hotpath + 总字节分配统计运行 galileo（默认执行 strategy）"
    vars:
      CMD: '{{default "strategy" .CMD}}'
    cmds:
      - cargo run --features="hotpath hotpath-alloc-bytes-total" -- {{.CMD}}

  pure_blind:cache:refresh:
    desc: "下载并校验纯盲市场缓存"
    cmds:
      - |
        {{- if .URL }}
        PURE_BLIND_MARKET_URL={{.URL}} ./scripts/pure_blind_cache.sh {{.OUTPUT | default "./cache/pure_markets.json"}}
        {{- else }}
        ./scripts/pure_blind_cache.sh {{.OUTPUT | default "./cache/pure_markets.json"}}
        {{- end }}
