# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: "默认执行 cargo check"
    cmds:
      - task: check

  check:
    desc: "执行 cargo check 确认编译通过"
    cmds:
      - cargo check

  build:
    desc: "编译项目（release 模式）"
    cmds:
      - cargo build --release

  galileo:run:
    desc: "运行 galileo CLI，自定义命令通过 CMD 变量传入"
    vars:
      CMD: "{{default \"--help\" .CMD}}"
    cmds:
      - cargo run -- {{.CMD}}

  galileo:help:
    desc: "查看 galileo CLI 帮助"
    cmds:
      - task: galileo:run
        vars:
          CMD: "--help"

  galileo:jupiter:help:
    desc: "查看 galileo jupiter 子命令帮助"
    cmds:
      - task: galileo:run
        vars:
          CMD: "jupiter --help"

  galileo:init:
    desc: "生成配置模版（支持额外参数传入）"
    cmds:
      - task: galileo:run
        vars:
          CMD: "init {{.CLI_ARGS | default \"\"}}"

  galileo:start:
    desc: "启动 Jupiter 二进制（可追加 --force-update）"
    cmds:
      - task: galileo:run
        vars:
          CMD: "jupiter start {{.CLI_ARGS | default \"\"}}"

  galileo:stop:
    desc: "停止 Jupiter 二进制"
    cmds:
      - task: galileo:run
        vars:
          CMD: "jupiter stop"

  galileo:restart:
    desc: "重启 Jupiter 二进制"
    cmds:
      - task: galileo:run
        vars:
          CMD: "jupiter restart"

  galileo:update:
    desc: "下载并安装最新的 Jupiter 二进制"
    cmds:
      - task: galileo:run
        vars:
          CMD: "jupiter update"

  galileo:status:
    desc: "查看 Jupiter 二进制当前状态"
    cmds:
      - task: galileo:run
        vars:
          CMD: "jupiter status"

  galileo:quote:
    desc: "请求 Jupiter 报价（需传入必要参数）"
    cmds:
      - task: galileo:run
        vars:
          CMD: "quote {{.CLI_ARGS | default \"--help\"}}"

  galileo:swap:
    desc: "请求 Jupiter Swap（需传入必要参数）"
    cmds:
      - task: galileo:run
        vars:
          CMD: "swap {{.CLI_ARGS | default \"--help\"}}"

  galileo:strategy:
    desc: "运行套利策略循环"
    cmds:
      - task: galileo:run
        vars:
          CMD: "strategy {{.CLI_ARGS | default \"\"}}"
