# https://taskfile.dev

version: "3"

tasks:
  check:
    desc: "执行 cargo check 确认编译通过"
    cmds:
      - cargo fmt
      - cargo check

  build:
    desc: "编译项目（release 模式）"
    cmds:
      - cargo build --release
  build:hotpath:
    desc: "编译项目（hotpath 模式）"
    cmds:
      - cargo build --release --features=hotpath

  build:hotpath-alloc-bytes:
    desc: "编译项目（hotpath + 总字节分配统计模式）"
    cmds:
      - cargo build --release --features="hotpath hotpath-alloc-bytes-total"

  galileo:run:
    desc: "运行 galileo CLI，自定义命令通过 CMD 变量传入"
    vars:
      CMD: '{{default "--help" .CMD}}'
    cmds:
      - cargo run -- {{.CMD}}

  galileo:help:
    desc: "查看 galileo CLI 帮助"
    cmds:
      - task: galileo:run
        vars:
          CMD: "--help"

  galileo:init:
    desc: "生成配置模版（支持额外参数传入）"
    cmds:
      - task: galileo:run
        vars:
          CMD: 'init {{.CLI_ARGS | default ""}}'

  galileo:quote:
    desc: "请求 Jupiter 报价（需传入必要参数）"
    cmds:
      - task: galileo:run
        vars:
          CMD: 'quote {{.CLI_ARGS | default "--help"}}'
  galileo:lander:
    desc: "运行上链器"
    cmds:
      - task: galileo:run
        vars:
          CMD: 'lander {{.CLI_ARGS | default ""}}'

  galileo:strategy:
    desc: "运行套利策略循环"
    cmds:
      - task: galileo:run
        vars:
          CMD: 'strategy {{.CLI_ARGS | default ""}}'

  galileo:jupiter:help:
    desc: "查看 galileo jupiter 子命令帮助"
    cmds:
      - task: galileo:run
        vars:
          CMD: "jupiter --help"

  galileo:jupiter:start:
    desc: "启动 Jupiter 二进制（可追加 --force-update）"
    cmds:
      - task: galileo:run
        vars:
          CMD: 'jupiter start {{.CLI_ARGS | default ""}}'

  galileo:jupiter:stop:
    desc: "停止 Jupiter 二进制"
    cmds:
      - task: galileo:run
        vars:
          CMD: "jupiter stop"

  galileo:jupiter:restart:
    desc: "重启 Jupiter 二进制"
    cmds:
      - task: galileo:run
        vars:
          CMD: "jupiter restart"

  galileo:jupiter:update:
    desc: "下载并安装最新 (或指定版本) 的 Jupiter 二进制"
    cmds:
      - task: galileo:run
        vars:
          CMD: 'jupiter update {{.CLI_ARGS | default ""}}'

  galileo:jupiter:status:
    desc: "查看 Jupiter 二进制当前状态"
    cmds:
      - task: galileo:run
        vars:
          CMD: "jupiter status"

  galileo:jupiter:list:
    desc: "列出最近可用的 Jupiter 版本"
    cmds:
      - task: galileo:run
        vars:
          CMD: 'jupiter list {{.CLI_ARGS | default ""}}'

  galileo:hotpath:
    desc: "启用 hotpath 特性运行 galileo（自定义命令通过 CMD 传入）"
    vars:
      CMD: '{{default "strategy" .CMD}}'
    cmds:
      - cargo run --features=hotpath -- {{.CMD}}

  galileo:hotpath:alloc-bytes:
    desc: "启用 hotpath + 总字节分配统计运行 galileo（默认执行 strategy）"
    vars:
      CMD: '{{default "strategy" .CMD}}'
    cmds:
      - cargo run --features="hotpath hotpath-alloc-bytes-total" -- {{.CMD}}
