version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: galileo-prometheus
    restart: unless-stopped
    user: "${PROMETHEUS_UID:-65534}:${PROMETHEUS_GID:-65534}"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.0.0
    container_name: galileo-grafana
    restart: unless-stopped
    user: "${GRAFANA_UID:-472}:${GRAFANA_GID:-0}"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_SERVER_DOMAIN=${GRAFANA_DOMAIN:-localhost}
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data:
